version: '3.9'
services:
  nginx:
    container_name: nginx-server
    image: 933006864322.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
    ports:
      - 6000:80
      - 6001:443
    restart: always
  webapi:
    container_name: clickmedicus-api
    image: 933006864322.dkr.ecr.ap-south-1.amazonaws.com/clickmedicus-api:10.0
    ports:
      - 3000:3000
    depends_on:
      - mysql-db
      - redis-db
    restart: always
    environment:
      - ACCESS_EXPIRY_TIME=60
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    ports:
      - ${MYSQL_PORT_DOCKER}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD_DOCKER}
    volumes:
      - mysql-data:/var/lib/mysql
  redis-db:
    container_name: redis-db
    image: redis:6.0
    restart: always
    ports:
      - ${REDIS_PORT_DOCKER}:6379
    command: 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD_DOCKER}'
volumes:
  mysql-data:
    driver: local
