version: '3.9'
services:
  # webapi:
  #   container_name: clickmedicus-api-dev
  #   build: .
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - redis-db
  #   restart: always
  # mysql-db:
  #   container_name: mysql-db-dev
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - ${MYSQL_PORT_DOCKER}:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD_DOCKER}
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  redis-db:
    container_name: redis-db-dev
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT_DOCKER}:6379
    command: 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD_DOCKER}'
# volumes:
#   mysql-data:
#     driver: local

# version: '3.9'

# volumes:
#   clickmedicus-mysql-data:
#     name: clickmedicus-mysql-data
#     driver: local

#   clickmedicus-redis-data:
#     name: clickmedicus-redis-data
#     driver: local

# networks:
#   clickmedicus-network:
#     name: clickmedicus-network
#     driver: bridge

# services:
#   webapi:
#     container_name: clickmedicus-webapi-dev
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     restart: on-failure
#     env_file:
#       - .env.development
#     ports:
#       - 3000:3000
#     networks:
#       - clickmedicus-network
#     # volumes:
#     #   - .:/home/app

#   mysql-db:
#     container_name: clickmedicus-mysql-db-dev
#     image: mysql:8.0
#     restart: unless-stopped
#     ports:
#       - ${MYSQL_PORT_DOCKER:-3306}:3306
#     env_file:
#       - .env.development
#     environment:
#       - MYSQL_DATABASE=${MYSQL_NAME}
#       - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD_DOCKER}
#     networks:
#       - clickmedicus-network
#     volumes:
#         - clickmedicus-mysql-data:/var/lib/mysql
#         - ./.sql:/docker-entrypoint-initdb.d/init-script.sql

#   redis-db:
#     container_name: clickmedicus-redis-db-dev
#     image: redis:7-alpine
#     restart: unless-stopped
#     ports:
#       - ${REDIS_PORT_DOCKER:-6379}:6379
#     command: ['redis-server', '--requirepass', '${REDIS_PASSWORD_DOCKER:-password-redis}']
#     volumes:
#       - clickmedicus-redis-data:/var/lib/redis
#     networks:
#       - clickmedicus-network