export enum ErrorCode {
	UNKNOWN_ERROR = 'UNKNOWN_ERROR',
	PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',
	EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
	INCORRECT_OLD_PASSWORD = 'INCORRECT_OLD_PASSWORD',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	INVARID_ID_ERROR = 'INVARID_ID_ERROR',
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	NOT_FOUND = 'NOT_FOUND',
	MEDICAL_RECORD_NOT_FOUND = 'MEDICAL_RECORD_NOT_FOUND',
	EMAIL_NOT_SENT = 'EMAIL_NOT_SENT',
	PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED'
}
